<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="UsbIp\_____UsbipDevice\**" />
    <EmbeddedResource Remove="UsbIp\_____UsbipDevice\**" />
    <None Remove="UsbIp\_____UsbipDevice\**" />
    <Page Remove="UsbIp\_____UsbipDevice\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="UsbIp\Protocol\OP_IMPORT_REQUEST.cs" />
    <Compile Remove="UsbIp\Protocol\OP_REP_IMPORT.cs" />
    <Compile Remove="UsbIp\Protocol\OP_REQ_DEVLIST.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="nlog.config" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.0.2" />
    <PackageReference Include="System.Formats.Cbor" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="nlog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
